/*
 * Kico API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"context"
	"log"
	"net/http"
	"os"
	"time"

	openapi "github.com/evrard-nil/kico/back-end/src/go"
	"go.mongodb.org/mongo-driver/mongo"
	"go.mongodb.org/mongo-driver/mongo/options"
)

const (
	// IcoDataFolderEnv represents the name of the environnement variable defining
	// where images and videos should be stored
	IcoDataFolderEnv = "ICO_DATA_STORAGE"
	// Port defines the listening port number
	port = "8080"
)

func main() {
	log.Printf("Server started")

	client, err := mongo.NewClient(options.Client().ApplyURI("mongodb://mongoadmin:secret@localhost:27100"))
	if err != nil {
		log.Fatal(err)
	}

	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	err = client.Connect(ctx)
	if err != nil {
		log.Fatal(err)
	}
	log.Printf("Mongo connection: OK")

	// Release resources at last
	defer cancel()
	defer client.Disconnect(ctx)

	dataFolder := os.Getenv(IcoDataFolderEnv)
	if dataFolder == "" {
		log.Fatalf("Data folder is not set up in environement variables. Check %s variable to set it up.", IcoDataFolderEnv)
	}

	APIService := openapi.NewAPIService(*client, dataFolder)
	APIController := openapi.NewDefaultAPIController(APIService)

	router := openapi.NewRouter(APIController)

	log.Printf("Starting to listen on %s.", port)
	log.Fatal(http.ListenAndServe(":"+port, router))
}
