openapi: 3.0.0
info:
  title: Kico API
  version: 0.0.0
servers:
- url: http://localhost.com/api/v1
paths:
  /videos:
    description: Allow to get informations concerning videos stored and their state.
    get:
      operationId: getVideos
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Video'
                type: array
          description: Videos
        default:
          description: Default error sample response
      summary: Retrieve all videos
    summary: Operations on videos
  /video/{id}:
    delete:
      operationId: deleteVideo
      parameters:
      - description: Numeric ID of the video to delete
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: integer
        style: simple
      responses:
        "200":
          description: Deletion sucessful
        default:
          description: Default error sample response
      summary: delete a video
    get:
      operationId: getVideo
      parameters:
      - description: Numeric ID of the video to get
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Video'
          description: A video
        default:
          description: Default error sample response
      summary: Retrieve a single video
    put:
      operationId: updateVideo
      parameters:
      - description: Numeric ID of the video to update
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: integer
        style: simple
      responses:
        "200":
          description: Update sucessful
        default:
          description: Default error sample response
      summary: Update a video
    summary: Operation on the video {id}
  /video:
    post:
      operationId: addVideo
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Video'
          description: A video
        default:
          description: Default error sample response
      summary: Add a  video
components:
  schemas:
    VideoState:
      description: State of a video
      enum:
      - imported
      - segmented
      - annotated
      nullable: false
      type: string
    Video:
      description: A video stored
      example:
        id: abc4
        url: https://www.youtube.com/watch?v=-5KAN9_CzSA
        date: '2017-07-21T17:32:28Z'
        scorePci: 14.5
        title: A great video
        state: imported
      nullable: false
      type: object
      properties:
        id:
          type: string
        state:
          $ref: '#/components/schemas/VideoState'
        annotatedBy: 
          type: string
        date: 
          type: string
          format: date-time
        scorePci: 
          type: number
        url:         
          type: string
        title: 
          type: string
    Image:
      description: An extracted image from a video
      type: object
      nullable: false
      properties:
        id: 
          type: number
        secteur_id: 
          type: number
        secteur_name: 
          type: string
        name:  
          type: string
        time:  
          type: string
        video_id:  
          type: number
