/*
 * Kico API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
)


// DefaultApiRouter defines the required methods for binding the api requests to a responses for the DefaultApi
// The DefaultApiRouter implementation should parse necessary information from the http request, 
// pass the data to a DefaultApiServicer to perform the required actions, then write the service results to the http response.
type DefaultApiRouter interface { 
	AddVideo(http.ResponseWriter, *http.Request)
	DeleteVideo(http.ResponseWriter, *http.Request)
	GetVideo(http.ResponseWriter, *http.Request)
	GetVideos(http.ResponseWriter, *http.Request)
	UpdateVideo(http.ResponseWriter, *http.Request)
}


// DefaultApiServicer defines the api actions for the DefaultApi service
// This interface intended to stay up to date with the openapi yaml used to generate it, 
// while the service implementation can ignored with the .openapi-generator-ignore file 
// and updated with the logic required for the API.
type DefaultApiServicer interface { 
	AddVideo(context.Context) (interface{}, error)
	DeleteVideo(context.Context, int32) (interface{}, error)
	GetVideo(context.Context, int32) (interface{}, error)
	GetVideos(context.Context) (interface{}, error)
	UpdateVideo(context.Context, int32) (interface{}, error)
}
