/*
 * Kico API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"errors"
	"log"
)

// DefaultApiService is a service that implents the logic for the DefaultApiServicer
// This service should implement the business logic for every endpoint for the DefaultApi API.
// Include any external packages or services that will be required by this service.
type DefaultApiService struct {
}

// NewDefaultApiService creates a default api service
func NewDefaultApiService() DefaultApiServicer {
	return &DefaultApiService{}
}

// AddVideo - Add a  video
func (s *DefaultApiService) AddVideo(ctx context.Context) (interface{}, error) {
	// TODO - update AddVideo with the required logic for this service method.
	log.Printf("AddVideo")
	return "OK", nil
}

// DeleteVideo - delete a video
func (s *DefaultApiService) DeleteVideo(ctx context.Context, id int32) (interface{}, error) {
	// TODO - update DeleteVideo with the required logic for this service method.

	return nil, errors.New("service method 'DeleteVideo' not implemented")
}

// GetVideo - Retrieve a single video
func (s *DefaultApiService) GetVideo(ctx context.Context, id int32) (interface{}, error) {
	log.Printf("GetVideo")
	return "OK", nil
}

// GetVideos - Retrieve all videos
func (s *DefaultApiService) GetVideos(ctx context.Context) (interface{}, error) {
	// TODO - update GetVideos with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'GetVideos' not implemented")
}

// UpdateVideo - Update a video
func (s *DefaultApiService) UpdateVideo(ctx context.Context, id int32) (interface{}, error) {
	// TODO - update UpdateVideo with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'UpdateVideo' not implemented")
}
