/*
 * Kico API
 *
 * This file describe the business logic of the kico api
 *
 * API version: 0.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"fmt"
	"log"
	"time"

	"go.mongodb.org/mongo-driver/mongo"
)

// APIService is a service that implents the logic for the DefaultApiServicer
// This service should implement the business logic for every endpoint for the DefaultApi API.
// Include any external packages or services that will be required by this service.
type APIService struct {
	dbClient mongo.Client
}

// NewAPIService creates a default api service
func NewAPIService(client mongo.Client) DefaultAPIServicer {
	return &APIService{dbClient: client}
}

// AddImageToVideo - Upload an image linked to a video
func (s *APIService) AddImageToVideo(ctx context.Context, id string, name string, secteurID string, time string, pid string, ext string) (interface{}, error) {
	log.Print("AddImageToVideo")

	url := "/images/" + pid + "." + ext

	picture := Image{
		ID:        pid,
		Name:      name,
		Time:      time,
		SecteurID: secteurID,
		URL:       url,
		VideoID:   id,
	}

	collection := s.dbClient.Database("ico").Collection("images")
	insertResult, err := collection.InsertOne(ctx, picture)

	if err != nil {
		print(err)
		return "Insertion error", err
	}
	fmt.Println("Inserted post with ID:", insertResult.InsertedID)

	return picture, nil
}

// AddVideo - Add a  video
func (s *APIService) AddVideo(ctx context.Context, title string, vid string, ext string) (interface{}, error) {
	log.Printf("AddVideo")

	url := "/videos/" + vid + "." + ext

	video := Video{
		ID:    vid,
		State: IMPORTED,
		Date:  time.Now(),
		Title: title,
		URL:   url,
	}

	collection := s.dbClient.Database("ico").Collection("videos")
	insertResult, err := collection.InsertOne(ctx, video)

	if err != nil {
		print(err)
		return "Insertion error", err
	}
	fmt.Println("Inserted post with ID:", insertResult.InsertedID)

	return video, nil
}

// DeleteImage - Deletes an image
func (s *APIService) DeleteImage(ctx context.Context, id string) (interface{}, error) {
	log.Printf("DeleteImage")
	return "OK", nil
}

// DeleteVideo - delete a video
func (s *APIService) DeleteVideo(ctx context.Context, id string) (interface{}, error) {
	log.Printf("DeleteVideo")
	return "OK", nil
}

// GetImage - Retrieve an image
func (s *APIService) GetImage(ctx context.Context, id string) (interface{}, error) {
	log.Printf("GetImage")
	return "OK", nil
}

// GetImagesFromVideo - Retrieve all images linked to a video
func (s *APIService) GetImagesFromVideo(ctx context.Context, id string) (interface{}, error) {
	log.Printf("GetImagesFromVideo")
	return "OK", nil
}

// GetVideo - Retrieve a single video
func (s *APIService) GetVideo(ctx context.Context, id string) (interface{}, error) {
	log.Printf("GetVideo")
	return "OK", nil
}

// GetVideos - Retrieve all videos
func (s *APIService) GetVideos(ctx context.Context) (interface{}, error) {
	log.Printf("GetVideos")
	return "OK", nil
}

// UpdateImage - update an image
func (s *APIService) UpdateImage(ctx context.Context, id string, image Image) (interface{}, error) {
	log.Printf("UpdateImage")
	return "OK", nil
}

// UpdateVideo - Update a video
func (s *APIService) UpdateVideo(ctx context.Context, id string, video Video) (interface{}, error) {
	log.Printf("UpdateVideo")
	return "OK", nil
}
