/*
 * Kico API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

// A DefaultApiController binds http requests to an api service and writes the service results to the http response
type DefaultApiController struct {
	service DefaultApiServicer
}

// NewDefaultApiController creates a default api controller
func NewDefaultApiController(s DefaultApiServicer) Router {
	return &DefaultApiController{service: s}
}

// Routes returns all of the api route for the DefaultApiController
func (c *DefaultApiController) Routes() Routes {
	return Routes{
		{
			"AddVideo",
			strings.ToUpper("Post"),
			"/api/v1/video",
			c.AddVideo,
		},
		{
			"DeleteVideo",
			strings.ToUpper("Delete"),
			"/api/v1/video/{id}",
			c.DeleteVideo,
		},
		{
			"GetVideo",
			strings.ToUpper("Get"),
			"/api/v1/video/{id}",
			c.GetVideo,
		},
		{
			"GetVideos",
			strings.ToUpper("Get"),
			"/api/v1/videos",
			c.GetVideos,
		},
		{
			"UpdateVideo",
			strings.ToUpper("Put"),
			"/api/v1/video/{id}",
			c.UpdateVideo,
		},
	}
}

// AddVideo - Add a  video
func (c *DefaultApiController) AddVideo(w http.ResponseWriter, r *http.Request) {
	result, err := c.service.AddVideo(r.Context())
	if err != nil {
		w.WriteHeader(500)
		return
	}

	EncodeJSONResponse(result, nil, w)
}

// DeleteVideo - delete a video
func (c *DefaultApiController) DeleteVideo(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	id, err := parseInt32Parameter(params["id"])
	if err != nil {
		w.WriteHeader(500)
		return
	}

	result, err := c.service.DeleteVideo(r.Context(), id)
	if err != nil {
		w.WriteHeader(500)
		return
	}

	EncodeJSONResponse(result, nil, w)
}

// GetVideo - Retrieve a single video
func (c *DefaultApiController) GetVideo(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	id, err := parseInt32Parameter(params["id"])
	if err != nil {
		w.WriteHeader(500)
		return
	}

	result, err := c.service.GetVideo(r.Context(), id)
	if err != nil {
		w.WriteHeader(500)
		return
	}

	EncodeJSONResponse(result, nil, w)
}

// GetVideos - Retrieve all videos
func (c *DefaultApiController) GetVideos(w http.ResponseWriter, r *http.Request) {
	result, err := c.service.GetVideos(r.Context())
	if err != nil {
		w.WriteHeader(500)
		return
	}

	EncodeJSONResponse(result, nil, w)
}

// UpdateVideo - Update a video
func (c *DefaultApiController) UpdateVideo(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	id, err := parseInt32Parameter(params["id"])
	if err != nil {
		w.WriteHeader(500)
		return
	}

	result, err := c.service.UpdateVideo(r.Context(), id)
	if err != nil {
		w.WriteHeader(500)
		return
	}

	EncodeJSONResponse(result, nil, w)
}
