/*
 * Kico API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Secteur - A secteur in abdomen
type Secteur struct {
	Index float32 `json:"index,omitempty" bson:"age"`

	Name string `json:"name,omitempty" bson:"age"`
}
