/*
 * Kico API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Video - A video stored
type Video struct {

	Id string `json:"id,omitempty"`

	Url string `json:"url,omitempty"`

	State VideoState `json:"state,omitempty"`
}
