/*
 * Kico API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Image - An extracted image from a video
type Image struct {
	ID string `json:"id,omitempty" bson:"_id"`

	SecteurID string `json:"secteur_id,omitempty" bson:"secteur_id"`

	Name string `json:"name,omitempty" bson:"name"`

	Time string `json:"time,omitempty" bson:"time"`

	VideoID string `json:"video_id,omitempty" bson:"video_id"`

	URL string `json:"url,omitempty" bson:"url"`

	Annotations [][][2]int `json:"annotations,omitempty" bson:"annotations"`
}
