/*
 * Kico API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"os"
)

type InlineObject1 struct {

	Name string `json:"name,omitempty"`

	FileName *os.File `json:"fileName,omitempty"`

	SecteurId string `json:"secteur_id,omitempty"`

	Time string `json:"time,omitempty"`
}
