/*
 * Kico API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Image - An extracted image from a video
type Image struct {

	Id float32 `json:"id,omitempty"`

	SecteurId float32 `json:"secteur_id,omitempty"`

	Name string `json:"name,omitempty"`

	Time string `json:"time,omitempty"`

	VideoId float32 `json:"video_id,omitempty"`
}
