/*
 * Kico API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

// Video - A video stored
type Video struct {
	ID string `json:"id,omitempty" bson:"_id"`

	State VideoState `json:"state,omitempty" bson:"state"`

	AnnotatedBy string `json:"annotated_by,omitempty" bson:"annotated_by"`

	Date time.Time `json:"date,omitempty" bson:"date"`

	ScorePCI float32 `json:"score_pci,omitempty" bson:"score_pci"`

	URL string `json:"url,omitempty" bson:"url"`

	Title string `json:"title,omitempty" bson:"title"`
}
